#!/bin/bash
if [ "$2" = "" ]; then
    exit
fi

if [ ! -f $1'Dockerfile.before' ]; then
    exit
fi

if [ ! -f $1'Dockerfile.after' ]; then
    exit
fi

/bin/bash $1'Dockerfile.before';

docker build -t $2 $1;

/bin/bash $1'Dockerfile.after';